# Oracle到Doris数据迁移系统配置

database:
  doris:
    host: "localhost"
    port: 9030
    user: "root"
    password: ""
    database: "migration_db"
    charset: "utf8mb4"
    
deepseek:
  api_key: "your_deepseek_api_key_here"
  base_url: "https://api.deepseek.com"
  model: "deepseek-reasoner"
  max_tokens: 4000
  temperature: 0.1
  timeout: 30
  
web_interface:
  host: "0.0.0.0"
  port: 5000
  debug: false
  secret_key: "your_secret_key_here"
  
migration:
  sample_lines: 100
  chunk_size_mb: 30
  max_workers: 8
  batch_size: 1000
  retry_count: 3
  enable_user_confirmation: true
  temp_dir: "./temp"
  
logging:
  level: "INFO"
  file: "migration.log"
  max_size_mb: 100
  backup_count: 5