-- 示例Oracle导出数据：产品表
INSERT INTO products (id, product_name, category, price, stock_quantity, description, created_date, last_updated, is_available, weight_kg) VALUES (1, 'iPhone 15 Pro', 'Electronics', 999.99, 50, 'Latest Apple smartphone with advanced features', TO_DATE('2023-09-15', 'YYYY-MM-DD'), TO_DATE('2024-01-20', 'YYYY-MM-DD'), 1, 0.187);
INSERT INTO products (id, product_name, category, price, stock_quantity, description, created_date, last_updated, is_available, weight_kg) VALUES (2, 'Samsung Galaxy S24', 'Electronics', 899.99, 75, 'Premium Android smartphone', TO_DATE('2023-10-10', 'YYYY-MM-DD'), TO_DATE('2024-01-19', 'YYYY-MM-DD'), 1, 0.195);
INSERT INTO products (id, product_name, category, price, stock_quantity, description, created_date, last_updated, is_available, weight_kg) VALUES (3, 'MacBook Pro 16"', 'Electronics', 2499.99, 25, 'High-performance laptop for professionals', TO_DATE('2023-11-05', 'YYYY-MM-DD'), TO_DATE('2024-01-18', 'YYYY-MM-DD'), 1, 2.15);
INSERT INTO products (id, product_name, category, price, stock_quantity, description, created_date, last_updated, is_available, weight_kg) VALUES (4, 'Nike Air Max 270', 'Footwear', 149.99, 120, 'Comfortable running shoes', TO_DATE('2023-08-20', 'YYYY-MM-DD'), TO_DATE('2024-01-15', 'YYYY-MM-DD'), 1, 0.8);
INSERT INTO products (id, product_name, category, price, stock_quantity, description, created_date, last_updated, is_available, weight_kg) VALUES (5, 'Adidas Ultraboost 22', 'Footwear', 179.99, 95, 'Premium running shoes with boost technology', TO_DATE('2023-09-01', 'YYYY-MM-DD'), TO_DATE('2024-01-16', 'YYYY-MM-DD'), 1, 0.85);
INSERT INTO products (id, product_name, category, price, stock_quantity, description, created_date, last_updated, is_available, weight_kg) VALUES (6, 'Sony WH-1000XM5', 'Electronics', 399.99, 60, 'Noise-cancelling wireless headphones', TO_DATE('2023-07-15', 'YYYY-MM-DD'), TO_DATE('2024-01-17', 'YYYY-MM-DD'), 1, 0.25);
INSERT INTO products (id, product_name, category, price, stock_quantity, description, created_date, last_updated, is_available, weight_kg) VALUES (7, 'The North Face Jacket', 'Clothing', 249.99, 40, 'Waterproof outdoor jacket', TO_DATE('2023-10-25', 'YYYY-MM-DD'), TO_DATE('2024-01-12', 'YYYY-MM-DD'), 1, 1.2);
INSERT INTO products (id, product_name, category, price, stock_quantity, description, created_date, last_updated, is_available, weight_kg) VALUES (8, 'Levi''s 501 Jeans', 'Clothing', 89.99, 200, 'Classic straight-leg jeans', TO_DATE('2023-06-10', 'YYYY-MM-DD'), TO_DATE('2024-01-10', 'YYYY-MM-DD'), 1, 0.6);
INSERT INTO products (id, product_name, category, price, stock_quantity, description, created_date, last_updated, is_available, weight_kg) VALUES (9, 'KitchenAid Stand Mixer', 'Home & Garden', 349.99, 30, 'Professional-grade stand mixer', TO_DATE('2023-11-20', 'YYYY-MM-DD'), TO_DATE('2024-01-14', 'YYYY-MM-DD'), 1, 10.5);
INSERT INTO products (id, product_name, category, price, stock_quantity, description, created_date, last_updated, is_available, weight_kg) VALUES (10, 'Dyson V15 Vacuum', 'Home & Garden', 749.99, 15, 'Cordless vacuum cleaner with laser detection', TO_DATE('2023-12-01', 'YYYY-MM-DD'), TO_DATE('2024-01-13', 'YYYY-MM-DD'), 1, 3.05);
INSERT INTO products (id, product_name, category, price, stock_quantity, description, created_date, last_updated, is_available, weight_kg) VALUES (11, 'Tesla Model Y Toy', 'Toys', 29.99, 500, 'Die-cast model car', TO_DATE('2023-05-15', 'YYYY-MM-DD'), TO_DATE('2024-01-11', 'YYYY-MM-DD'), 1, 0.15);
INSERT INTO products (id, product_name, category, price, stock_quantity, description, created_date, last_updated, is_available, weight_kg) VALUES (12, 'Organic Green Tea', 'Food & Beverage', 12.99, 1000, '100% organic green tea leaves', TO_DATE('2023-04-20', 'YYYY-MM-DD'), TO_DATE('2024-01-09', 'YYYY-MM-DD'), 1, 0.1);
INSERT INTO products (id, product_name, category, price, stock_quantity, description, created_date, last_updated, is_available, weight_kg) VALUES (13, 'Yoga Mat Premium', 'Sports', 79.99, 80, 'Non-slip premium yoga mat', TO_DATE('2023-08-05', 'YYYY-MM-DD'), TO_DATE('2024-01-08', 'YYYY-MM-DD'), 1, 1.8);
INSERT INTO products (id, product_name, category, price, stock_quantity, description, created_date, last_updated, is_available, weight_kg) VALUES (14, 'Office Chair Ergonomic', 'Furniture', 299.99, 45, 'Ergonomic office chair with lumbar support', TO_DATE('2023-09-30', 'YYYY-MM-DD'), TO_DATE('2024-01-07', 'YYYY-MM-DD'), 1, 15.2);
INSERT INTO products (id, product_name, category, price, stock_quantity, description, created_date, last_updated, is_available, weight_kg) VALUES (15, 'Gaming Monitor 27"', 'Electronics', 449.99, 35, '4K gaming monitor with high refresh rate', TO_DATE('2023-12-15', 'YYYY-MM-DD'), TO_DATE('2024-01-06', 'YYYY-MM-DD'), 1, 5.8);